name: Project Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Build React Frontend
      run: |
        cd rc-client
        npm ci
        npm run build
    - name: Copy React Build to Quarkus App static folder
      run: |
        mkdir -p rc-server/src/main/resources/static
        cp -r rc-client/dist* rc-server/src/main/resources/static/

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
  
    - name: Build with Maven
      run: |
        cd rc-server
        mvn clean install

    - uses: superfly/flyctl-actions/setup-flyctl@master


    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
